package com.example.cooky.util

const val STRING_COMMA = ","
const val NONE = ""
const val DEFAULT_ID = 0
const val ON_EXPAND = -1
const val ON_COLLAPSING = 0
const val ROTATE_DURATION = 100L
const val ROTATE_INVERSE = 180f
const val ROTATE_DEFAULT = 0f
const val MAX_RECENTLY_RECIPES = 8
const val INDEX_FIRST = 0
const val RECENTLY_ID = "recently id"
const val STRING_NULL = "null"
const val TITLE_DIET_ALL = "all"
const val TITLE_DIET_GLUTEN_FREE = "Gluten Free"
const val TITLE_DIET_KETOGENIC = "Ketogenic"
const val TITLE_DIET_VEGETARIAN = "Vegetarian"
const val TITLE_DIET_PESCETARIAN = "Pescetarian"
const val TITLE_DIET_PALEO = "Paleo"
const val TITLE_DIET_WHOLE30 = "Whole30"
const val NUMBER_MIN_TARGET_CALOS = 500
const val BREAKFAST_INDEX = 0
const val LUNCH_INDEX = 1
const val DINNER_INDEX = 2
const val QUERY_NUMBER_DEFAULT = 20
const val FIRST_THUMP_INDEX = 0
const val NUTRIENT_OPTION = "nutrient option"
const val NUMBER_PER_LOADING = 10
